### ISSUE TITLE
Howto Use?

### ISSUE THREAD

**Issue by uppaljs** [cgrates-web/cgrates_web_frontend#6]
Hi,

Can you kindly put out a small guide on setting this up? I am interested in using and / contribute in testing if required.

**Comment by max-konin** [comment]
Hi.

This project under active development. I will write a guide a little bit later..

**Comment by ykh** [comment]
@max-konin 
Hi.
We want use this project (tnx for this opensource app) in production! Is it ready for production?

**Comment by max-konin** [comment]
@ykh It depends on your CGRates version. I have not updated this project for a long time. You can try to use it and post an issue here if something will not work

**Comment by marcin11** [comment]
Please provide default user/pass to access log in page

**Comment by max-konin** [comment]
@marcin11 admin@example.com/password

**Comment by WaledEzzi** [comment]
Hello ,

I tried accessing the web with the above (admin@example.com/password) but no luck ,
Could you provide the exact one, since I am using a container .

Thank you in advance
Waled

**Comment by max-konin** [comment]
Hi @WaledEzzi Have you installed backend and executed migrations https://github.com/cgrates-web/cgrates_web_jsonapi/blob/master/README.md?s

**Comment by WaledEzzi** [comment]
Thank you @max-konin for your response.

Actually, I am working on the docker of **cgrates_web_frontend** not this **cgrates_web_jsonapi** 

And I am suing this docker image :
https://hub.docker.com/r/maxkonin/cgrates_web_frontend

Could you please guide how to login to this cgrates_web_frontend ..

**Comment by max-konin** [comment]
@WaledEzzi you need to also install the backend cgrates_web_jsonapi, it has nessesary setup for the database and credentials
[See this gist https://gist.github.com/max-konin/4d812441e2658215793b6c581d7d124b for ](https://gist.github.com/max-konin/4d812441e2658215793b6c581d7d124b) - example config for docker compose

**Comment by WaledEzzi** [comment]
Thank you So so much for your guidance ..
So we have now 3 containers (PG DB) ,,(cgrates_web_jsonapi) ,,(cgrates_web_frontend)..

and i should use the container of cgrates itself right ,by the way i am using mysql in it?

Is there any link for the below docker compose with the container of CGRATES and its DB or its belong only to first DB in the below compose file :
I am referring to these parameters:

  SECRET_KEY_BASE: 123 # Your SECRET KEY. Can be generated manualy
      GUARDIAN_SECRET_KEY: # Your SECRET KEY for JWT. Can be generated manualy
      DB_USER: # PG user
      DB_PASSWORD: # PG password
      DB_HOST: database
      DB_DATABASE: cgrates # dataDB's name
      CGRATES_URL: # URL of our cgrates API instance
      CGRATES_TENANT: "cgrates.org" # TENANT
      CGRATES_USERNAME: # user for access to CGrateS API
      CGRATES_PASSWORD: # password for access to CGrateS API




version: "3"

services:
  database:
    image: postgres
    container_name: pgsql
    ports:
      - "5432:5432"
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 3

  cgrates_web_jsonapi:
    image: maxkonin/cgrates_web_jsonapi
    container_name: cgrates_web_jsonapi
    ports:
      - "4000:8000"
    environment:
      HOST: localhost
      SECRET_KEY_BASE: 123 # Your SECRET KEY. Can be generated manualy
      GUARDIAN_SECRET_KEY: # Your SECRET KEY for JWT. Can be generated manualy
      DB_USER: # PG user
      DB_PASSWORD: # PG password
      DB_HOST: database
      DB_DATABASE: cgrates # dataDB's name
      CGRATES_URL: # URL of our cgrates API instance
      CGRATES_TENANT: "cgrates.org" # TENANT
      CGRATES_USERNAME: # user for access to CGrateS API
      CGRATES_PASSWORD: # password for access to CGrateS API
    depends_on:
      - database

  cgrates_web_frontend:
    image: maxkonin/cgrates_web_frontend
    container_name: cgrates_web_frontend
    entrypoint: "/root/docker-entrypoint.sh"
    ports:
      - "80:80"
    environment:
      API_HOST: "http://<your-domain-for-backend>:4000"

**Comment by WaledEzzi** [comment]
Hello @max-konin 

Kindly find my compose file ,and .env for all ..

But there is an issue need your help kindly and thank you in advance ..



[FRONT.zip](https://github.com/cgrates-web/cgrates_web_frontend/files/12717314/FRONT.zip)
[logs.txt](https://github.com/cgrates-web/cgrates_web_frontend/files/12717342/logs.txt)

**Comment by WaledEzzi** [comment]
Update:

Please ignore all previous comments/logs..
Kindly have a look at the attached config and output logs as I cant log in to the frontend ..
Please have a look and please support accessing the Frontend ...Kindly ..

NOTE:I Have added the cgrates container (5gs_ocs) with IP 172.23.0.40  so you might have a look on all confi so you guide us with the correct steps  please ..
[logs.zip](https://github.com/cgrates-web/cgrates_web_frontend/files/12719081/logs.zip)

**Comment by WaledEzzi** [comment]
dear @max-konin :

Kindly Kindly i need only 5 min of your time as I am a little bit confused ..
Could you please have a call on google meer for only 5 min ..
If yes please specify a suitable time for you..

Thank you in advance
Waled

**Comment by max-konin** [comment]
@WaledEzzi 
1. This project does not support mysql, only postgress
2. ` DB_DATABASE: postgres` don't use `postgres` as a new of your database, use your own schema. 
3. You have to run migrations as I guide above https://github.com/cgrates-web/cgrates_web_jsonapi/blob/master/README.md?s

FYI: I've not been contributed to this project for 2 years. It may not be compatible with the latest version of cgrates

**Comment by WaledEzzi** [comment]
Hello @max-konin 

Thank you so much for your feedback..
NO issue with the new changes on Cgrates project we can adapt ..
But I am still facing problem login to the frontend ,even i did the my best :) for building the compose file ..

OCS_IP=172.23.0.40

DB_IP=172.23.0.43
BACK_IP=172.23.0.44
FRONT_IP=172.23.0.45

Please find the logs that i am getting and the compose file i used ...
Kindly help me out to sort this issue ..

Can we have a chat for short time  to try fixing it..
[Printscreen_compos.zip](https://github.com/cgrates-web/cgrates_web_frontend/files/13044012/Printscreen_compos.zip)

**Comment by WaledEzzi** [comment]
@max-konin 

Kindly to help here as still, I think a small thing and with your support, we can sort it out ..

Please and sorry for bothering you..

Warm Regards,
Waled

**Comment by max-konin** [comment]
@WaledEzzi See documentation for the official postgres image https://hub.docker.com/_/postgres. The default user is `postgres` but you set it as `DB_USER: cgrates` for the backend conainer.

PS: If you still have questions about your specific case, reach me via email plz. I'm gonna close this issue

**Comment by WaledEzzi** [comment]
Thank you Max Konin for your support,i am sorry that i am bothering you ..

Have you looked at the error I sent "its
vendor-9b38400df78ee85a69320ff41cb32326.js:5258     POST
http://172.23.0.44:4000/sessions net::ERR_CONNECTION_REFUSED"   <----this
IP is the IP of backend container)..


*With regards to postgres user :*
*But my database is: cgrates*
*                   Username:cgrates*
*                   Password:CGRateS.org*

and I can access it successfully with these information i mentioned above :
***@***.***:/home/waled1/Music/FRONT_TRY# docker exec -it pgsql bash
***@***.***:/#
***@***.***:/# psql -d cgrates -U cgrates -W
Password:   <================================ I inserted this
password:CGRateS.org
psql (16.0 (Debian 16.0-1.pgdg120+1))
Type "help" for help.

cgrates=>
cgrates=>
cgrates=>
cgrates=>
cgrates=> \dt
                 List of relations
 Schema |          Name          | Type  |  Owner
--------+------------------------+-------+---------
 public | cdrs                   | table | cgrates
 public | raw_supplier_rates     | table | cgrates
 public | schema_migrations      | table | cgrates
 public | session_costs          | table | cgrates
 public | tariff_plans           | table | cgrates
 public | tenants                | table | cgrates
 public | tp_account_actions     | table | cgrates
 public | tp_action_plans        | table | cgrates
 public | tp_action_profiles     | table | cgrates
 public | tp_action_triggers     | table | cgrates
 public | tp_actions             | table | cgrates
 public | tp_attributes          | table | cgrates
 public | tp_chargers            | table | cgrates
 public | tp_destination_rates   | table | cgrates
 public | tp_destinations        | table | cgrates
 public | tp_dispatcher_profiles | table | cgrates
 public | tp_filters             | table | cgrates
 public | tp_rate_profiles       | table | cgrates
 public | tp_rates               | table | cgrates
 public | tp_rating_plans        | table | cgrates
 public | tp_rating_profiles     | table | cgrates
 public | tp_resources           | table | cgrates
 public | tp_routes              | table | cgrates
 public | tp_shared_groups       | table | cgrates
 public | tp_stats               | table | cgrates
 public | tp_thresholds          | table | cgrates
 public | tp_timings             | table | cgrates
 public | users                  | table | cgrates
 public | versions               | table | cgrates
(29 rows)

cgrates=> select * from users;
 id |       email       |                      password_encrypted
           |     inserted_at     |     updated_at      |  tenant_id
----+-------------------+--------------------------------------------------------------+---------------------+---------------------+-------------
  1 | ***@***.*** |
$2b$12$zjs4XZPLnNrF41FcceSCZe0lWrBbp1mVXI3o6O1aeT7yFuhDkdwGm | 2023-09-28
20:54:09 | 2023-09-28 20:54:09 | cgrates.org
(1 row)

cgrates=>
